Rely on HTML spec for deadline computation
w3c/requestidlecallback pull request #95
Opened 2021-10-07 05:16 UTC by noamr

In conjunction with https://github.com/whatwg/html/pull/7166

Instead of defining the idle period deadline in prose, rely on the
event model processing in the HTML spec to provide a more precise
computation of the current idle period deadline.

This is accomplished by passing a `getDeadline` algorithm from the HTML
spec to this spec when starting an idle period, and re-computing that
deadline between idle callbacks, or when `timeRemaining()` is called.

This ensures (more formally) that adding timeouts that expire before
the end of the idle period, or `requestAnimationFrame` calls from
within the idle period, which currently are specified to fire before
the next idle tasks due to event loop priorities, will also be reflected
when calling `timeRemaining`.

Closes #71

2021-10-07 08:28 UTC, yoavweiss commented on index.html
>          <li>Let <var>deadline</var> be a time in the future until which the
Should this be dropped? |deadline| is no longer used, right?

2021-10-11 08:03 UTC, marcoscaceres commented on index.html
> +      <p>To <dfn export>start an idle period</dfn> given {{Window}} <var>window</var> and
```suggestion
      <p>To <dfn class="export">start an idle period</dfn> given {{Window}} <var>window</var> and
```

2021-10-11 08:04 UTC, marcoscaceres commented on index.html
> +      <p>Each <a>IdleDeadline</a> has an associated <dfn>time getter</dfn>, an algorithm that
You should be able to do: 

```suggestion
      <p>Each {{IdleDeadline}} has an associated <dfn>time getter</dfn>, an algorithm that
```

Globally

2021-10-11 08:07 UTC, marcoscaceres commented on index.html
> +      <var>getDeadline</var>, an algorithm that returns a {{DOMHighResTimeStamp}}: [[HR-TIME]]
The reading is a little bit confusing... the type usually comes first:

```suggestion
      an algorithm that returns a {{DOMHighResTimeStamp}} <var>getDeadline</var>: [[HR-TIME]]
```

2021-10-11 08:08 UTC, marcoscaceres commented on index.html
> +      by the <a data-cite="html#event-loop-processing-model">event loop processing model</a>
Note: If you have `data-cite="html...` it means something is probably not right (or needs to be exported from HTML!).

2021-10-11 08:08 UTC, marcoscaceres commented on index.html
> +      by the <a data-cite="html#event-loop-processing-model">event loop processing model</a>
(unless it's a heading 😅 ... as I've not implemented xrefs for those in ReSpec yet!)

2021-10-11 08:09 UTC, noamr commented on index.html
> +      by the <a data-cite="html#event-loop-processing-model">event loop processing model</a>
Yea, this was here before and I've moved it around

2021-10-11 08:10 UTC, marcoscaceres commented on index.html
> +      an algorithm that returns a {{DOMHighResTimeStamp}} <var>getDeadline</var>: [[HR-TIME]]
Nit: Matter of editorial preference, but I tend not to add dangling references like ": [[HR-TIME]]" around the place... but it's up to you.

2021-10-11 08:11 UTC, marcoscaceres reviewed
I only gave this a "respec review", as I'm not very familiar with requestidlecallback... however, if you want a proper review, I can dive a little deeper in requestidlecallback.

2021-10-11 08:14 UTC, noamr commented
> I only gave this a "respec review", as I'm not very familiar with requestidlecallback... however, if you want a proper review, I can dive a little deeper in requestidlecallback.

Not necessary, we will discuss it in TPAC and people more familiar with it can review together with the corresponding HTML-spec changes. Thanks for the editorial review!

2021-11-17 18:06 UTC, noamr commented
@yoavweiss I think this is ready for an actual review, now that the corresponding HTML PR has landed.

2021-11-18 07:04 UTC, marcoscaceres requested changes

2021-11-18 07:04 UTC, marcoscaceres commented on index.html
> +      milliseconds of the deadline, initially set to return zero.
How about?: 

```suggestion
      <p>Each {{IdleDeadline}} has an associated <dfn>get deadline time</dfn> algorithm, which
      returns a {{DOMHighResTimeStamp}} representing the absolute time in
      milliseconds of the deadline. The deadline is initially set to return zero.
```

Random suggestion... but ignore if "get deadline time" is custom algorithm that is passed. 

However, it might be better to just have a "get deadline time" algorithm that takes an {{IdleDeadline}} instance and gives back a DOMHighResTimeStamp. I.e.:

```TS
function getTimeStamp(deadLine: IdleDeadline) => DOMHighResTimeStamp {
    // do stuff with IdleDeadline
    return timestamp.
}
```

2021-11-18 07:04 UTC, marcoscaceres commented on index.html
> +        algorithm associated with the <a>IdleDeadline</a> object.</li>
Maybe better:

```suggestion
        <li>Let <var>deadline</var> be the result of calling {{IdleDeadline}}'s <a>get deadline time</a> algorithm.</li>
```

However, can we get {{IdleDeadline}} into a variable? it should really be:

```
       <li>Let |deadline| be the result of calling |idleDeadline|'s [=get deadline time=] algorithm.</li>
```

2021-11-18 07:04 UTC, marcoscaceres commented on index.html
> +        device. For example, if the {{Document}}'s is {{Document/hidden}} then the user agent can
```suggestion
        device. For example, if the {{Document}}'s [=Document/visibility state=] is "hidden" then the user agent can
```

2021-11-18 12:46 UTC, noamr commented on index.html
> +      milliseconds of the deadline, initially set to return zero.
It is a custom algorithm that is passed from the HTML spec... so I don't think this suggestion is applicable.

2021-11-19 09:45 UTC, yoavweiss approved these changes
LGTM

2021-11-19 12:54 UTC, noamr commented
@marcoscaceres any changes still requested?

2021-11-22 09:27 UTC, marcoscaceres commented
No, apologies for the delay.

2021-11-22 09:28 UTC, merged